import { Check, Download, FileText, RotateCcw, Save, ThumbsDown, ThumbsUp } from 'lucide-react'
import { useState } from 'react'
import type { DetectionResult as Result } from '../types/detection'
import { DetectionOverlay } from './DetectionOverlay'

interface DetectionResultProps {
  result: Result
  onCheckAnother: () => void
  onSave: () => void
  saved: boolean
}

export function DetectionResult({ result, onCheckAnother, onSave, saved }: DetectionResultProps) {
  const [feedback, setFeedback] = useState<'yes' | 'no' | null>(null)
  const found = result.detections.length > 0
  const highest = result.detections[0]?.confidence ?? 0

  function downloadAnnotated() {
    const image = new Image()
    image.src = result.imageUrl
    image.onload = () => {
      const canvas = document.createElement('canvas')
      canvas.width = image.naturalWidth
      canvas.height = image.naturalHeight
      const context = canvas.getContext('2d')
      if (!context) return
      context.drawImage(image, 0, 0)
      result.detections.forEach((detection, index) => {
        const box = detection.boundingBox
        const x = (box.x / 100) * canvas.width
        const y = (box.y / 100) * canvas.height
        const width = (box.width / 100) * canvas.width
        const height = (box.height / 100) * canvas.height
        context.strokeStyle = '#ef6a4a'
        context.lineWidth = Math.max(4, canvas.width / 180)
        context.strokeRect(x, y, width, height)
        context.fillStyle = '#ef6a4a'
        context.font = `bold ${Math.max(20, canvas.width / 42)}px sans-serif`
        context.fillText(`${index + 1} · ${Math.round(detection.confidence * 100)}%`, x, Math.max(24, y - 10))
      })
      const link = document.createElement('a')
      link.download = `loon-check-${result.fileName}`
      link.href = canvas.toDataURL('image/jpeg', 0.92)
      link.click()
    }
  }

  return (
    <div className="result-layout">
      <section className={`result-banner ${found ? 'result-found' : 'result-clear'}`}>
        <div className="result-icon">{found ? <Check size={22} /> : <FileText size={22} />}</div>
        <div>
          <p className="eyebrow">Check complete</p>
          <h1>{found ? `${result.detections.length} ${result.detections.length === 1 ? 'loon' : 'loons'} detected` : 'No loon detected'}</h1>
          <p>{found ? `We found ${result.detections.length === 1 ? 'a loon' : `${result.detections.length} loons`} in this image.` : "We didn't find a loon in this image."}</p>
        </div>
      </section>

      <section className="result-main-grid">
        <div className="result-image-column">
          <DetectionOverlay imageUrl={result.imageUrl} detections={result.detections} alt={`Analyzed image: ${result.fileName}`} />
          <p className="image-caption">{found ? 'Highlighted areas show where a loon was found.' : 'Review the image carefully when accuracy is important.'}</p>
        </div>
        <div className="details-column">
          {found ? <>
            <div className="detail-heading"><span className="status-dot" /> Detection details</div>
            <div className="confidence-card">
              <div className="confidence-top"><span>Highest confidence</span><strong>{Math.round(highest * 100)}%</strong></div>
              <div className="confidence-track"><span style={{ width: `${highest * 100}%` }} /></div>
              <p>Confidence indicates how strongly the model matched this image to a loon.</p>
            </div>
            <div className="detection-list">
              {result.detections.map((detection, index) => <div className="detection-row" key={detection.id}><span><b>{index + 1}</b> Loon</span><strong>{Math.round(detection.confidence * 100)}%</strong></div>)}
            </div>
          </> : <div className="clear-note"><p>This result is generated by an AI model and may not always be correct.</p><button className="button button-dark" onClick={onCheckAnother}><RotateCcw size={17} /> Try another image</button></div>}
          <details className="details-disclosure"><summary>View details</summary><dl><div><dt>File name</dt><dd>{result.fileName}</dd></div><div><dt>Date analyzed</dt><dd>{new Date(result.timestamp).toLocaleString()}</dd></div><div><dt>Processing time</dt><dd>{result.processingTime.toFixed(1)} seconds</dd></div></dl></details>
        </div>
      </section>

      <section className="result-actions">
        <button className="button button-dark" onClick={onCheckAnother}><RotateCcw size={17} /> Check another image</button>
        <button className="button button-outline" onClick={onSave} disabled={saved}><Save size={17} /> {saved ? 'Saved to history' : 'Save result'}</button>
        <button className="button button-quiet" onClick={downloadAnnotated}><Download size={17} /> Download image</button>
      </section>
      <section className="feedback-row"><span>Was this result helpful?</span><button className={`feedback-button ${feedback === 'yes' ? 'selected' : ''}`} onClick={() => setFeedback('yes')}><ThumbsUp size={15} /> Yes</button><button className={`feedback-button ${feedback === 'no' ? 'selected' : ''}`} onClick={() => setFeedback('no')}><ThumbsDown size={15} /> No</button></section>
    </div>
  )
}
